name: Deploy Next.js App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install dependencies using Yarn
        run: yarn install

      - name: Build Next.js app using Yarn
        run: yarn build
