name: Deploy Next.js App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install dependencies using Yarn
        run: yarn install --frozen-lockfile

      - name: Create env.local file
        run: |
          echo "AUTH0_SECRET='${{ secrets.AUTH0_SECRET }}'" > env.local
          echo "AUTH0_BASE_URL='${{ secrets.AUTH0_BASE_URL }}'" >> env.local
          echo "AUTH0_ISSUER_BASE_URL='${{ secrets.AUTH0_ISSUER_BASE_URL }}'" >> env.local
          echo "AUTH0_CLIENT_ID='${{ secrets.AUTH0_CLIENT_ID }}'" >> env.local
          echo "AUTH0_CLIENT_SECRET='${{ secrets.AUTH0_CLIENT_SECRET }}'" >> env.local

      - name: Build Next.js app using Yarn
        run: yarn build
